{{- if .Values.crds.install }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ansiblejobs.a5e.k8s.rocks
  annotations:
    {{- if .Values.crds.keep }}
    helm.sh/resource-policy: keep
    {{- end }}
spec:
  group: a5e.k8s.rocks
  scope: Namespaced
  names:
    kind: AnsibleJob
    listKind: AnsibleJobList
    plural: ansiblejobs
    singular: ansiblejob
    shortNames:
      - ansiblejob
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Schedule
          jsonPath: .spec.schedule
          type: string
        - name: Suspend
          jsonPath: .spec.suspend
          type: boolean
        - name: LastSchedule
          jsonPath: .status.lastScheduleTime
          type: date
        - name: Age
          jsonPath: .metadata.creationTimestamp
          type: date
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                template:
                  type: object
                  properties:
                    playbookRef:
                      type: object
                      properties:
                        apiGroup:
                          type: string
                          default: a5e.k8s.rocks
                        kind:
                          type: string
                          enum:
                            - AnsiblePlaybook
                            - ClusterAnsiblePlaybook
                        name:
                          type: string
                        namespace:
                          type: string
                      required:
                        - kind
                        - name
                    inventoryRef:
                      type: object
                      properties:
                        apiGroup:
                          type: string
                          default: a5e.k8s.rocks
                        kind:
                          type: string
                          enum:
                            - AnsibleInventory
                            - ClusterAnsibleInventory
                        name:
                          type: string
                        namespace:
                          type: string
                      required:
                        - kind
                        - name
                    extraVars:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    ansibleOptions:
                      type: object
                      properties:
                        verbosity:
                          type: integer
                          minimum: 0
                          maximum: 4
                        tags:
                          type: array
                          items:
                            type: string
                        skipTags:
                          type: array
                          items:
                            type: string
                        limit:
                          type: string
                        checkMode:
                          type: boolean
                        forks:
                          type: integer
                          minimum: 1
                    timeoutSeconds:
                      type: integer
                      exclusiveMinimum: true
                      minimum: 0
                    ttlSecondsAfterFinished:
                      type: integer
                      minimum: 0
                    serviceAccountName:
                      type: string
                    resources:
                      type: object
                      properties:
                        limits:
                          type: object
                          additionalProperties:
                            type: string
                        requests:
                          type: object
                          additionalProperties:
                            type: string
                  required:
                    - playbookRef
                    - inventoryRef
                schedule:
                  type: string
                suspend:
                  type: boolean
                  default: false
                concurrencyPolicy:
                  type: string
                  enum:
                    - Allow
                    - Forbid
                    - Replace
                  default: Allow
                successfulRunsHistoryLimit:
                  type: integer
                  minimum: 0
                  default: 3
                failedRunsHistoryLimit:
                  type: integer
                  minimum: 0
                  default: 1
              required:
                - template
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum:
                          - "True"
                          - "False"
                          - Unknown
                      reason:
                        type: string
                      message:
                        type: string
                      observedGeneration:
                        type: integer
                      lastTransitionTime:
                        type: string
                    required:
                      - type
                      - status
                      - reason
                      - message
                      - lastTransitionTime
                  x-kubernetes-list-type: map
                  x-kubernetes-list-map-keys:
                    - type
                lastScheduleTime:
                  type: string
                lastRunRef:
                  type: object
                  properties:
                    name:
                      type: string
                  required:
                    - name
                active:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                    required:
                      - name
{{- end }}
