{{- if and .Values.api.oidc.create (not .Values.api.oidc.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "a5e.oidcSecretName" . }}
  namespace: {{ include "a5e.namespace" . }}
  labels:
    {{- include "a5e.componentLabels" (list . "api") | nindent 4 }}
type: Opaque
stringData:
  issuer: {{ .Values.api.oidc.issuer | quote }}
  clientId: {{ .Values.api.oidc.clientId | quote }}
  clientSecret: {{ .Values.api.oidc.clientSecret | quote }}
{{- end }}
---
{{- if and .Values.s3.create (not .Values.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "a5e.s3SecretName" . }}
  namespace: {{ include "a5e.namespace" . }}
  labels:
    {{- include "a5e.labels" . | nindent 4 }}
type: Opaque
stringData:
  bucket: {{ .Values.s3.bucket | quote }}
  accessKeyId: {{ .Values.s3.accessKeyId | quote }}
  secretAccessKey: {{ .Values.s3.secretAccessKey | quote }}
  endpoint: {{ .Values.s3.endpoint | quote }}
  region: {{ .Values.s3.region | quote }}
{{- end }}
