server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://a5e-api.a5e-system.svc.cluster.local/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_buffering off; # needed for SSE (watch/logs streams)
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
